[package]
name = "tailscale-vita-demo"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
vita-log     = { path = "../vita-log" }
wg-engine    = { path = "../wg-engine" }
netstack     = { path = "../netstack" }
ts-control   = { path = "../ts-control" }
ts-derp      = { path = "../ts-derp" }
smoltcp      = { workspace = true }
x25519-dalek = { workspace = true }
parking_lot  = { workspace = true }
tracing      = { workspace = true }
http         = "1"

[package.metadata.vita]
title_id   = "TVIT00010"
title_name = "Tailscale-Vita Demo"
vita_make_fself_flags = []
