[package]
name = "netstack"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
smoltcp           = { workspace = true }
vita-sync         = { path = "../vita-sync" }
vita-log = { path = "../vita-log" }
thiserror         = { workspace = true }
wg-engine         = { path = "../wg-engine" }
vita-thread       = { path = "../vita-thread" }
